captive_portal:

web_server:
    port: 80
    log: False
    ota: False

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

switch:
  - platform: template
    name: "Virtual Lock Port 1"
    id: virtual_lock_door1
    optimistic: true
  - platform: template
    name: "Virtual Lock Port 2"
    id: virtual_lock_door2
    optimistic: true
  - platform: gpio
    pin: GPIO5
    name: "Garagedoor 2 D1"
    id: door_relay_door2
    internal: true
    on_turn_on:
    - delay: 250ms
    - switch.turn_off: door_relay_door2
  - platform: gpio
    pin: GPIO4
    name: "Garagedoor 1 D2"
    id: door_relay_door1
    internal: true
    on_turn_on:
    - delay: 250ms
    - switch.turn_off: door_relay_door1

binary_sensor:
  - platform: status
    name: "Connect"
  - platform: template
    name: "Garagedoor 2 status"
    id: is_jammed_door2
    device_class: problem
  - platform: template
    name: "Garagedoor 2"
    id: is_open_door2
    device_class: garage_door
  - platform: template
    name: "Garagedoor 1 status"
    id: is_jammed_door1
    device_class: problem
  - platform: template
    name: "Garagedoor 1"
    id: is_open_door1
    device_class: garage_door

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garagedoor 2 Lukket sensor D3"
    id: close_endstop_binary_sensor_door2
    internal: true
    on_press:
       - cover.template.publish:
           id: garage_door_door2
           state: CLOSED
           current_operation: IDLE
       - binary_sensor.template.publish:
          id: is_jammed_door2
          state: OFF
       - binary_sensor.template.publish:
          id: is_open_door2
          state: OFF
    on_release: 
       - cover.template.publish:
           id: garage_door_door2
           current_operation: OPENING    
       - binary_sensor.template.publish:
          id: is_open_door2
          state: ON
       - delay: 25s
       - if:
           condition:
             binary_sensor.is_off: open_endstop_binary_sensor_door2
           then: 
              - binary_sensor.template.publish:
                  id: is_jammed_door2
                  state: ON
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garagedoor 2 Åpen sensor D4"
    id: open_endstop_binary_sensor_door2
    internal: true
    on_press:
       - cover.template.publish:
           id: garage_door_door2
           state: OPEN
           current_operation: IDLE
       - binary_sensor.template.publish:
          id: is_jammed_door2
          state: OFF
    on_release: 
       - cover.template.publish:
           id: garage_door_door2
           current_operation: CLOSING  
       - delay: 25s
       - if:
           condition:
             binary_sensor.is_off: close_endstop_binary_sensor_door2
           then: 
              - binary_sensor.template.publish:
                  id: is_jammed_door2
                  state: ON
  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garagedoor 1 Lukket sensor D5"
    id: close_endstop_binary_sensor_door1
    internal: true
    on_press:
       - cover.template.publish:
           id: garage_door_door1
           state: CLOSED
           current_operation: IDLE
       - binary_sensor.template.publish:
          id: is_jammed_door1
          state: OFF
       - binary_sensor.template.publish:
          id: is_open_door1
          state: OFF
    on_release: 
       - cover.template.publish:
           id: garage_door_door1
           current_operation: OPENING    
       - binary_sensor.template.publish:
          id: is_open_door1
          state: ON
       - delay: 25s
       - if:
           condition:
             binary_sensor.is_off: open_endstop_binary_sensor_door1
           then: 
              - binary_sensor.template.publish:
                  id: is_jammed_door1
                  state: ON
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Garagedoor 1 Åpen sensor D6"
    id: open_endstop_binary_sensor_door1
    internal: true
    on_press:
       - cover.template.publish:
           id: garage_door_door1
           state: OPEN
           current_operation: IDLE
       - binary_sensor.template.publish:
          id: is_jammed_door1
          state: OFF
    on_release: 
       - cover.template.publish:
           id: garage_door_door1
           current_operation: CLOSING  
       - delay: 25s
       - if:
           condition:
             binary_sensor.is_off: close_endstop_binary_sensor_door1
           then: 
              - binary_sensor.template.publish:
                  id: is_jammed_door1
                  state: ON


sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name:  "Upime"

cover:
  - platform: template
    id: garage_door_door2
    name: "Garagedoor 2"
    device_class: garage
    open_action:
        - if:
           condition:
             - and:
               - switch.is_off: virtual_lock_door2
               - binary_sensor.is_on: close_endstop_binary_sensor_door2
           then: 
             - switch.turn_on: door_relay_door2
    close_action:
      - if:
           condition:
             - and:
               - switch.is_off: virtual_lock_door2
               - binary_sensor.is_on: open_endstop_binary_sensor_door2
           then: 
             - switch.turn_on: door_relay_door2
    stop_action:
      - if:
           condition:
             - and:
               - switch.is_off: virtual_lock_door2
               - binary_sensor.is_off: close_endstop_binary_sensor_door2
               - binary_sensor.is_off: open_endstop_binary_sensor_door2
           then: 
             - switch.turn_on: door_relay_door2
  - platform: template
    id: garage_door_door1
    name: "Garagedoor 1"
    device_class: garage
    open_action:
        - if:
           condition:
             - and:
               - switch.is_off: virtual_lock_door1
               - binary_sensor.is_on: close_endstop_binary_sensor_door1
           then: 
             - switch.turn_on: door_relay_door1
    close_action:
      - if:
           condition:
             - and:
               - switch.is_off: virtual_lock_door1
               - binary_sensor.is_on: open_endstop_binary_sensor_door1
           then: 
             - switch.turn_on: door_relay_door1
    stop_action:
      - if:
           condition:
             - and:
               - switch.is_off: virtual_lock_door1
               - binary_sensor.is_off: close_endstop_binary_sensor_door1
               - binary_sensor.is_off: open_endstop_binary_sensor_door1
           then: 
             - switch.turn_on: door_relay_door1